# Generated by Django 4.0.4 on 2022-05-23 20:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_number', models.IntegerField()),
                ('instructor_name', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
            ],
            managers=[
                ('djangoClasses', django.db.models.manager.Manager()),
            ],
        ),
    ]
