# Generated by Django 4.0.4 on 2022-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='fname',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=50),
        ),
    ]
